name: On PR

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run repository tests
        run: python3 -m unittest

  trigger-review:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Trigger package review
        run: |
          python3 review-bot.py \
          --pr-url ${{ github.event.pull_request.url }} \
          --base-sha ${{ github.event.pull_request.base.sha }} \
          --token ${{ secrets.GITHUB_TOKEN }}
